[package]
name = "stock-bot"
version = "0.1.0"
authors = ["Chris Butler <chrisbutler296@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "^0.8"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

[dependencies.serenity]
default-features = true
version = "^0.5"
