[package]
name = "stock-bot"
version = "0.1.0"
authors = ["Chris Butler <chrisbutler296@gmail.com>"]
edition = "2018"

[dependencies]
curl = '^0.4'
json = '^0.11'

[dependencies.serenity]
default-features = true
version = "^0.5"
